export interface LessonBeat {
  night: number;
  theme: string;       // short label for the completion card
  prompt: string;      // injected into story generation prompt
}

export interface CreatureDef {
  id: string;
  name: string;
  emoji: string;
  color: string;
  description: string;
  nameSuggestions: string[];
  // Dreamkeeper system
  virtue: string;              // the moral theme this creature teaches
  craft: string;               // always 'constellation'
  craftName: string;           // unique constellation name (e.g. 'The Bunny')
  craftEmoji: string;          // always '✦'
  storyPersonality: string;    // how the creature behaves in stories (for AI prompt)
  virtueKeywords: string[];    // maps story lessons to this creature
  // Constellation — 7 star positions in a ~100x100 viewBox
  constellationPoints: [number,number][];
  lessonBeats: LessonBeat[];   // 7 progressive lessons
  dailyWisdom: string[];       // 7 homepage speech lines (indexed by egg night)
}

export const CREATURES: CreatureDef[] = [
  {
    id:'bunny', name:'Moon Bunny', emoji:'🐰', color:'#F5B84C',
    description:'soft, moonlit, impossibly fluffy',
    nameSuggestions:['Luna','Mochi','Pip','Star'],
    virtue:'Courage', craft:'constellation', craftName:'The Bunny', craftEmoji:'✦',
    constellationPoints:[[35,5],[30,30],[50,38],[70,30],[65,5],[40,60],[60,60]],
    storyPersonality:'Timid but willing to try. Speaks in short, warm sentences. Hides behind the hero at first but steps forward when it matters. Models courage through small quiet acts rather than big dramatic ones.',
    virtueKeywords:['courage','bravery','brave','fear','facing fears','scared','afraid'],
    lessonBeats:[
      {night:1, theme:'The shape of being scared', prompt:'Explore what fear feels like in the body — the weight, the temperature, the way it sits. Treat it as a landscape the character moves through, not a problem to solve.'},
      {night:2, theme:'Giving the fear a name', prompt:'The story wanders into the territory of naming — what happens when you say the scary thing out loud. The act of naming is the event, not a lesson about naming.'},
      {night:3, theme:'The smallest brave thing', prompt:'The story explores the space between wanting to move and actually moving. One small step — not heroic, not triumphant, just real. The step IS the story.'},
      {night:4, theme:'What falling feels like', prompt:'The story sits inside the experience of trying and failing — not to teach that failure is okay, but to show what it actually feels like, and what comes after.'},
      {night:5, theme:'Seeing someone else\'s scared', prompt:'The story explores what it feels like to recognise fear in someone else — the strange bravery of noticing, of reaching out, of being the one who understands.'},
      {night:6, theme:'The courage that was already there', prompt:'The story explores the discovery that readiness was building quietly all along — not a revelation delivered, but a recognition that arrives.'},
      {night:7, theme:'The quiet kind', prompt:'The story lives in the territory of everyday, undramatic courage — staying, speaking, trying again. Not a victory. A choice, small and real.'},
    ],
    dailyWisdom:[
      "Did you know? Being scared and being brave are the same feeling.",
      "If you can name the scary thing, it gets a little smaller. Try it.",
      "You don't have to jump. You just have to step.",
      "The bravest people aren't the ones who never fall.",
      "Know what's really brave? Helping someone else try.",
      "You've been ready for this longer than you think.",
      "Courage isn't loud. Sometimes it's just staying.",
    ],
  },
  {
    id:'fox', name:'Ember Fox', emoji:'🦊', color:'#FF8264',
    description:'clever, warm, a little mischievous',
    nameSuggestions:['Ember','Russet','Maple','Blaze'],
    virtue:'Cleverness', craft:'constellation', craftName:'The Fox', craftEmoji:'✦',
    constellationPoints:[[20,30],[35,15],[55,20],[75,10],[80,35],[65,55],[45,70]],
    storyPersonality:'Quick-witted and playful. Sees solutions others miss. Sometimes too clever for their own good. Learns that the smartest answer isn\'t always the trickiest one.',
    virtueKeywords:['cleverness','clever','problem solving','thinking','smart','creative thinking','wit'],
    lessonBeats:[
      {night:1, theme:'The texture of looking twice', prompt:'The story explores what it feels like to look again — the moment between glancing and truly seeing. Not a lesson about paying attention, but the landscape of noticing itself.'},
      {night:2, theme:'The weight of why', prompt:'The story wanders into the territory of questioning — what happens when "why" lands in a room full of "because." The asking is the event, not the answer it produces.'},
      {night:3, theme:'The door that isn\'t a door', prompt:'The story sits inside the space between the stuck place and the unexpected way through. Not a celebration of cleverness — just the strange feeling of a sideways thought arriving.'},
      {night:4, theme:'The beautiful wreckage of a plan', prompt:'The story explores what it feels like when a clever idea falls apart — the mess, the surprise, the odd gifts hiding inside the failure. The wreckage is the territory.'},
      {night:5, theme:'Where two ideas touch', prompt:'The story wanders into the space where one person\'s thinking meets another\'s — the friction, the spark, the thing that neither could have built alone. Collaboration as landscape, not lesson.'},
      {night:6, theme:'The plainness of the real answer', prompt:'The story explores the feeling of arriving at something simple after wandering through complexity — the quiet surprise of "oh, it was just this." Simplicity as territory.'},
      {night:7, theme:'The quiet of knowing when to stop', prompt:'The story lives in the space between cleverness and stillness — what it feels like to have the trick ready but choose to set it down. Not a moral about wisdom. The choosing itself.'},
    ],
    dailyWisdom:[
      "The best answers are hiding in the places nobody thinks to look.",
      "Why? is the most powerful word you'll ever learn.",
      "When the door is locked, check the window.",
      "Every mistake is a clue in disguise.",
      "Your idea plus their idea makes a better idea.",
      "Sometimes the answer is so simple you almost miss it.",
      "Being clever is good. Being wise is better.",
    ],
  },
  {
    id:'dragon', name:'Storm Drake', emoji:'🐉', color:'#60C8A0',
    description:'fierce, magical, secretly gentle',
    nameSuggestions:['Zephyr','Sprig','Kite','Ember'],
    virtue:'Resilience', craft:'constellation', craftName:'The Dragon', craftEmoji:'✦',
    constellationPoints:[[15,50],[30,25],[50,15],[70,20],[85,40],[70,65],[40,75]],
    storyPersonality:'Fierce on the outside, surprisingly tender. Gets knocked down a lot. Always gets back up. Has a quiet stubbornness that looks like strength. Never gives a speech about resilience — just does it.',
    virtueKeywords:['resilience','perseverance','never giving up','persistence','tough','bouncing back','grit','determination'],
    lessonBeats:[
      {night:1, theme:'The weight of a hard thing', prompt:'The story explores what a hard thing actually feels like when it arrives — its weight, its shape, the way the air changes. Not rushing past it. Just being in the room with it.'},
      {night:2, theme:'Sitting inside the feeling', prompt:'The story wanders into the territory of a difficult feeling that wants to be pushed away — what happens when it\'s allowed to stay instead. The sitting-with is the landscape.'},
      {night:3, theme:'The space between giving up and trying again', prompt:'The story explores the strange middle place where trying again isn\'t certain and quitting doesn\'t fit — the wobbly moment of choosing to move, not because of hope, but because of something quieter.'},
      {night:4, theme:'What resting actually looks like', prompt:'The story sits inside the act of stopping — the guilt, the relief, the slow return of something. Not a message about rest being strength. Just the texture of pausing when everything says keep going.'},
      {night:5, theme:'The feeling of leaning', prompt:'The story explores what it feels like to let someone else hold some of the weight — the strange vulnerability of it, the lightness after. The leaning is the territory, not a lesson about asking for help.'},
      {night:6, theme:'The shape of something mended', prompt:'The story wanders into the territory of broken-and-repaired things — the seam, the scar, the unexpected beauty of what grew back different. Not a metaphor delivered. A thing observed.'},
      {night:7, theme:'The existence of tomorrow', prompt:'The story lives in the quiet territory of not-yet-solved — the feeling of knowing tomorrow is there, and that\'s enough. Not a resolution. An exhale.'},
    ],
    dailyWisdom:[
      "Hard things happen. That part isn't your fault.",
      "You don't have to be okay right now. Just be here.",
      "One more try doesn't mean you're not tired. It means you're brave.",
      "Resting isn't giving up. It's getting ready.",
      "Even dragons ask for help sometimes.",
      "Broken things that heal are stronger than things that never broke.",
      "Tomorrow is a whole new sky.",
    ],
  },
  {
    id:'owl', name:'Dusk Owl', emoji:'🦉', color:'#9A7FD4',
    description:'wise, watchful, full of secrets',
    nameSuggestions:['Sage','Dusk','Merlin','Hoot'],
    virtue:'Wisdom', craft:'constellation', craftName:'The Owl', craftEmoji:'✦',
    constellationPoints:[[50,10],[30,30],[70,30],[25,55],[75,55],[40,80],[60,80]],
    storyPersonality:'Quiet observer who notices everything. Speaks rarely but every word matters. Never tells the hero what to do — asks questions that help them figure it out themselves.',
    virtueKeywords:['wisdom','wise','choices','decisions','thinking before acting','judgement','understanding'],
    lessonBeats:[
      {night:1, theme:'The pause before knowing', prompt:'The story explores what happens in the moment of stopping — the way the world opens when rushing ends. Not a lesson about noticing. The pause itself as landscape.'},
      {night:2, theme:'What silence holds', prompt:'The story wanders into the space that opens when talking stops — what lives inside listening, the things that can only be heard when the mouth is still. Silence as territory.'},
      {night:3, theme:'The other side of a thing', prompt:'The story explores the disorienting feeling of something being different than it appeared — the wobble, the recalibration, the strangeness of seeing clearly. Not a trick reveal. A shift in the ground.'},
      {night:4, theme:'The long way around', prompt:'The story sits inside the tension of choosing the harder path now — what it feels like to walk past the easy thing toward the better-but-later thing. The tension is the territory.'},
      {night:5, theme:'Wisdom in unlikely places', prompt:'The story explores what it feels like to be taught by someone unexpected — the surprise of it, the humility, the way knowing can arrive from anywhere. The encounter, not the lesson.'},
      {night:6, theme:'The shape of a good question', prompt:'The story wanders into the territory of questions that matter more than their answers — what a question opens, the doors it finds, the way it changes the room. The asking as landscape.'},
      {night:7, theme:'The comfort of not knowing', prompt:'The story lives in the wide, quiet territory of uncertainty — what it feels like to stand in "I don\'t know" and find it peaceful instead of frightening. Not resolution. Spaciousness.'},
    ],
    dailyWisdom:[
      "The world tells you things all day. Most people forget to listen.",
      "Your ears are older than your mouth. Use them first.",
      "Things aren't always what they look like from here.",
      "The easy choice and the right choice are rarely the same.",
      "Everyone you meet knows something you don't.",
      "A good question is worth more than a quick answer.",
      "The wisest words in any language: I don't know yet.",
    ],
  },
  {
    id:'bear', name:'Frost Bear', emoji:'🐻', color:'#90C8E8',
    description:'cosy, strong, warmth itself',
    nameSuggestions:['Frost','Birch','Cloud','Pudding'],
    virtue:'Kindness', craft:'constellation', craftName:'The Bear', craftEmoji:'✦',
    constellationPoints:[[35,15],[65,15],[20,40],[80,40],[50,50],[30,78],[70,78]],
    storyPersonality:'Warm, gentle, and solid. Gives the best hugs in any story. Notices when someone is cold, hungry, or lonely before anyone else does. Kindness is automatic, not performed.',
    virtueKeywords:['kindness','kind','caring','compassion','helping','empathy','gentle','thoughtful'],
    lessonBeats:[
      {night:1, theme:'The seeing before the helping', prompt:'The story explores the moment of noticing — what it feels like when someone\'s need becomes visible, the quiet pull of it. Not a lesson about paying attention. The noticing itself as landscape.'},
      {night:2, theme:'The size of a small thing', prompt:'The story wanders into the territory of tiny gestures — the surprising weight of something barely done, the way a small kindness can fill a room. The smallness is the territory.'},
      {night:3, theme:'The strange work of being gentle with yourself', prompt:'The story explores what it feels like to turn kindness inward — the awkwardness, the unfamiliarity, the way self-gentleness can feel harder than any outward generosity.'},
      {night:4, theme:'Kindness that costs something', prompt:'The story sits inside the difficulty of being kind when it doesn\'t come easily — the friction, the choice, the way it feels in the body to extend warmth toward coldness.'},
      {night:5, theme:'The kindness nobody sees', prompt:'The story explores the territory of invisible generosity — what it feels like to do something kind with no witness, no credit, no return. The privacy of it. The fullness.'},
      {night:6, theme:'The difficulty of receiving', prompt:'The story wanders into the uncomfortable space of being on the receiving end — the instinct to refuse, the vulnerability of accepting, the way letting someone give to you is its own kind of gift.'},
      {night:7, theme:'Where kindness goes after you let it go', prompt:'The story lives in the territory of ripples moving outward — kindness that travels beyond the giver\'s sight, changing rooms the giver will never enter. Not a moral. A quiet unfolding.'},
    ],
    dailyWisdom:[
      "Look around. Someone near you could use a friend right now.",
      "The smallest things you do are sometimes the biggest things to someone else.",
      "Be as kind to yourself as you are to your favourite person.",
      "Being kind to someone who wasn't kind to you? That's the real thing.",
      "The best kind things are the ones nobody sees.",
      "Letting someone help you is a gift to them too.",
      "One kind thing becomes a hundred kind things. You just don't see them all.",
    ],
  },
  {
    id:'cat', name:'Shadow Cat', emoji:'🐱', color:'#A090D0',
    description:'curious, independent, secretly snuggly',
    nameSuggestions:['Misty','Nimbus','Pixel','Wisp'],
    virtue:'Independence', craft:'constellation', craftName:'The Cat', craftEmoji:'✦',
    constellationPoints:[[25,20],[45,10],[65,15],[80,30],[70,55],[50,75],[30,60]],
    storyPersonality:'Walks their own path. Comfortable being different. Not rebellious — just quietly certain. Shows that independence means knowing who you are, not pushing others away.',
    virtueKeywords:['independence','confident','self-belief','being yourself','different','unique','standing alone'],
    lessonBeats:[
      {night:1, theme:'The feeling of turning away from the crowd', prompt:'The story explores the moment of choosing a different direction — the pull of the group, the uncertainty in the chest, the strange honesty of a separate path. The turning is the territory.'},
      {night:2, theme:'The shape of your own way', prompt:'The story wanders into the landscape of doing things differently — what it feels like when your particular approach fits perfectly, the rightness of your own strange shape.'},
      {night:3, theme:'The fullness of alone', prompt:'The story explores solitude as a place — its texture, its sounds, the unexpected richness of one\'s own company. Not a lesson about being okay alone. The aloneness itself, full and real.'},
      {night:4, theme:'A voice that doesn\'t match the room', prompt:'The story sits inside the moment of saying something different from everyone else — the held breath, the steadiness, the way a true thought feels in the throat before it leaves.'},
      {night:5, theme:'Choosing to come back', prompt:'The story explores the territory of returning — what it feels like to have walked alone and then choose connection again. Independence that includes reaching back. The choosing is the landscape.'},
      {night:6, theme:'The sound of your own knowing', prompt:'The story wanders into the space between what everyone says and what something deeper insists — the instinct, the belly-feeling, the quiet certainty that lives underneath the noise.'},
      {night:7, theme:'All the contradictions at once', prompt:'The story lives in the territory of being many things simultaneously — soft and strong, separate and connected, sure and uncertain. Not a resolution of opposites. The wholeness of holding them all.'},
    ],
    dailyWisdom:[
      "Just because everyone else is going that way doesn't mean you have to.",
      "Your way of doing things? It's not wrong. It's yours.",
      "Sometimes the best company is your own.",
      "It's okay to think something different. Say it gently and mean it.",
      "Being independent doesn't mean being alone. It means choosing.",
      "That feeling in your belly that says 'this way'? Trust it.",
      "You can be soft and strong. Quiet and brave. All of it. All at once.",
    ],
  },
  {
    id:'wolf', name:'Moon Wolf', emoji:'🐺', color:'#88B0D8',
    description:'loyal, fierce, runs with the stars',
    nameSuggestions:['Ash','Gale','Storm','Silver'],
    virtue:'Loyalty', craft:'constellation', craftName:'The Wolf', craftEmoji:'✦',
    constellationPoints:[[20,60],[35,35],[50,20],[70,15],[85,30],[75,55],[55,75]],
    storyPersonality:'Devoted and protective. Runs ahead to check the path is safe, then comes back. Shows loyalty through action — being there — not words. Has a quiet intensity.',
    virtueKeywords:['loyalty','loyal','trust','promise','showing up','reliable','dependable','commitment'],
    lessonBeats:[
      {night:1, theme:'The weight of just being there', prompt:'The story explores what presence feels like — the simple act of being in the room, saying nothing, fixing nothing, just being there. Presence as territory, not performance.'},
      {night:2, theme:'What a promise feels like from inside', prompt:'The story wanders into the landscape of a kept word — the inconvenience, the pull to break it, the strange solidity of following through when it would be easier not to.'},
      {night:3, theme:'Standing beside', prompt:'The story explores the feeling of choosing a side — not the politics of it, but the physical sensation of planting your feet next to someone when the wind is against them.'},
      {night:4, theme:'The loyalty of disagreeing', prompt:'The story sits inside the complicated territory of loving someone you think is wrong — the tension between "I\'m still here" and "I don\'t agree." The staying despite, not because.'},
      {night:5, theme:'Trust built in tiny layers', prompt:'The story explores the slow accumulation of trust — small consistent moments stacking like snow, none dramatic, all necessary. The patience of it. The dailiness.'},
      {night:6, theme:'Staying after the letdown', prompt:'The story wanders into the territory of forgiveness within loyalty — what it feels like when someone you chose lets you down, and you choose them again. Not a lesson about forgiveness. The choosing again.'},
      {night:7, theme:'What was noticed all along', prompt:'The story lives in the quiet territory of loyalty that was witnessed without the giver knowing — the way steady presence leaves marks on people. Not a reward. A recognition that arrives.'},
    ],
    dailyWisdom:[
      "Sometimes the bravest thing is just showing up.",
      "A promise is a promise. Even the small ones.",
      "Standing next to someone when things are hard — that's everything.",
      "Real loyalty isn't agreeing. It's staying.",
      "Trust is built in tiny moments. Every single one counts.",
      "People make mistakes. Staying is a choice you make every time.",
      "The people who matter remember every time you showed up.",
    ],
  },
  {
    id:'unicorn', name:'Dream Unicorn', emoji:'🦄', color:'#E8A8D8',
    description:'magical, rare, makes wishes real',
    nameSuggestions:['Aurora','Shimmer','Opal','Celestia'],
    virtue:'Imagination', craft:'constellation', craftName:'The Unicorn', craftEmoji:'✦',
    constellationPoints:[[40,10],[55,5],[70,20],[75,45],[60,65],[40,70],[25,45]],
    storyPersonality:'Sees magic everywhere others see ordinary. Turns puddles into oceans and blankets into mountains. Not naive — genuinely creative. Shows that imagination is a superpower, not childishness.',
    virtueKeywords:['imagination','creative','creativity','wonder','dreaming','ideas','make-believe','pretend'],
    lessonBeats:[
      {night:1, theme:'The shimmer of something not yet there', prompt:'The story explores the moment before creation — the feeling of something wanting to exist, the shimmer at the edge of thought. Not a lesson about imagination. The territory of almost-seeing.'},
      {night:2, theme:'The secret life of ordinary things', prompt:'The story wanders into the hidden world inside everyday objects — the stories a spoon could tell, the dreams a doorknob might hold. The ordinary as landscape, alive and layered.'},
      {night:3, theme:'The road that starts with what if', prompt:'The story explores the feeling of a "what if" taking root — where it leads, how the ground shifts, the unexpected country that opens when one question is followed honestly.'},
      {night:4, theme:'Beauty from the discarded', prompt:'The story sits inside the act of making — the way thrown-away things become something else under patient hands. Not a lesson about creativity. The transformation itself, its texture and warmth.'},
      {night:5, theme:'Letting someone into your world', prompt:'The story explores the vulnerability of sharing an inner world with another person — the risk, the intimacy, the way a private landscape changes when someone else walks through it.'},
      {night:6, theme:'The substance of belief', prompt:'The story wanders into the territory of believing in the not-yet-possible — what belief feels like in the body, its weight and warmth, the way it bends the air around itself.'},
      {night:7, theme:'The way you see', prompt:'The story lives in the territory of seeing itself — the particular magic of one person\'s gaze, the way the world is different because of who is looking at it. Not a revelation. A settling-in.'},
    ],
    dailyWisdom:[
      "Close your eyes. What do you see? That's where we're going tonight.",
      "That boring thing in the corner? Look again. It's full of secrets.",
      "What if the sky was made of something else? What would you choose?",
      "You don't need fancy things. You need fancy ideas.",
      "The best worlds are the ones you share with someone.",
      "If you believe it hard enough, it starts to become real.",
      "The magic was never in the wand. It was in you the whole time.",
    ],
  },
  {
    id:'panda', name:'Cloud Panda', emoji:'🐼', color:'#B0A0D8',
    description:'gentle giant, nap champion',
    nameSuggestions:['Mochi','Bao','Nori','Snowdrop'],
    virtue:'Patience', craft:'constellation', craftName:'The Panda', craftEmoji:'✦',
    constellationPoints:[[35,15],[65,15],[20,40],[80,40],[35,65],[65,65],[50,85]],
    storyPersonality:'Calm, unhurried, and completely content to wait. Never rushes. Treats every moment as enough. Shows that patience isn\'t passive — it\'s choosing to trust that things take time.',
    virtueKeywords:['patience','patient','waiting','calm','peaceful','still','slow','mindful'],
    lessonBeats:[
      {night:1, theme:'What rushing feels like', prompt:'The story explores the sensation of speed — the blur, the missed things, the way the world narrows when you move too fast. Then the widening when you stop. The contrast is the territory.'},
      {night:2, theme:'The particular sweetness of waiting', prompt:'The story wanders into the landscape of anticipation — the ache of it, the restlessness, and then the particular quality of something that arrives because you didn\'t grab for it.'},
      {night:3, theme:'One breath as a room', prompt:'The story explores a single breath as a space you can step inside — the way everything rearranges when the body pauses, the room that exists between inhale and exhale.'},
      {night:4, theme:'The pace of growing things', prompt:'The story sits inside the slow unfolding of something that cannot be hurried — the dailiness of tending, the invisible movement, the faith required to keep watering what you cannot yet see.'},
      {night:5, theme:'What the quiet has been holding', prompt:'The story explores what lives inside silence — the things that can only be heard when all the noise stops, the way patience opens a door that effort never could.'},
      {night:6, theme:'The rightness of late arrivals', prompt:'The story wanders into the territory of things that come in their own time — the frustration of waiting, and then the strange perfection of the timing, understood only afterward.'},
      {night:7, theme:'The completeness of right now', prompt:'The story lives in a single, unhurried moment — not building toward anything, not leaving anything behind. The feeling of here being enough. Not contentment taught. Contentment inhabited.'},
    ],
    dailyWisdom:[
      "What's the rush? The good stuff happens when you slow down.",
      "The best things come to those who wait. Truly.",
      "When everything feels too much, just breathe. That's enough for now.",
      "You can't make a flower grow faster by pulling it. Just water it.",
      "Shh. Hear that? The quiet has something to tell you.",
      "It'll come. Maybe not today. But it'll come.",
      "Right here, right now, this moment — it's enough.",
    ],
  },
  {
    id:'deer', name:'Star Deer', emoji:'🦌', color:'#D4A860',
    description:'graceful, gentle, golden light',
    nameSuggestions:['Fawn','Maple','Solstice','Flicker'],
    virtue:'Gratitude', craft:'constellation', craftName:'The Deer', craftEmoji:'✦',
    constellationPoints:[[50,10],[35,25],[65,25],[30,50],[70,50],[40,80],[60,80]],
    storyPersonality:'Graceful and gentle. Stops to appreciate small beautiful things others walk past. Not preachy about gratitude — just naturally notices the good. Makes others slow down and see it too.',
    virtueKeywords:['gratitude','grateful','thankful','appreciation','noticing','blessing','thankfulness'],
    lessonBeats:[
      {night:1, theme:'The good thing you almost walked past', prompt:'The story explores the moment of catching something good before it slips by — the near-miss of it, the way a day changes when one bright detail is truly seen. The noticing as landscape.'},
      {night:2, theme:'What thank you feels like when you mean it', prompt:'The story wanders into the territory of real gratitude spoken aloud — the vulnerability, the specificity, the way it changes the air between two people. Not politeness. The raw thing.'},
      {night:3, theme:'The hidden warmth inside difficulty', prompt:'The story explores the strange geography of a hard time — and the unexpected warm thing tucked inside it. Not a silver-lining lesson. The act of finding warmth in cold territory.'},
      {night:4, theme:'The person behind everything', prompt:'The story sits inside the feeling of looking at what matters most and finding a face there — the way people outweigh things, the weight of a particular someone in the landscape of a life.'},
      {night:5, theme:'Making someone feel seen', prompt:'The story explores the act of showing someone they are noticed and valued — what it feels like to be the one who says "I see you." The seeing as territory.'},
      {night:6, theme:'Your ordinary Tuesday, seen fresh', prompt:'The story wanders through the most familiar landscape — the everyday, the routine — but with new eyes. The extraordinary hidden inside the completely normal. Not a lesson about perspective. The dazzle of the plain.'},
      {night:7, theme:'The fullness of exactly this', prompt:'The story lives in the territory of having enough — not wanting more, not reviewing less. The quiet, steady feeling of exactly what is. Not a conclusion about gratitude. The fullness itself.'},
    ],
    dailyWisdom:[
      "What's one good thing that happened today? There's always one.",
      "When you say thank you, look them in the eyes. It changes everything.",
      "Even hard days are hiding something good. Can you find it?",
      "The best things in your life aren't things.",
      "Someone did something kind for you today. Did you notice?",
      "Your regular Tuesday? Somebody somewhere is wishing for it.",
      "You have enough. You are enough. Right now.",
    ],
  },
  {
    id:'frog', name:'Dream Frog', emoji:'🐸', color:'#80C870',
    description:'happy, bouncy, always optimistic',
    nameSuggestions:['Mossy','Puddle','Dewdrop','Lily'],
    virtue:'Joy', craft:'constellation', craftName:'The Frog', craftEmoji:'✦',
    constellationPoints:[[30,25],[50,10],[70,25],[80,50],[60,70],[40,70],[20,50]],
    storyPersonality:'Irrepressibly happy. Finds delight in puddles, mud, rain, bugs — things others find gross or boring. Not naive — genuinely joyful. Shows that joy is a choice and a practice, not luck.',
    virtueKeywords:['joy','happiness','happy','fun','delight','cheerful','optimism','positive','silly'],
    lessonBeats:[
      {night:1, theme:'The fun hiding inside the boring', prompt:'The story explores the moment delight surfaces in an unlikely place — the way joy can be found tucked inside the dull and ordinary, waiting for someone to turn it over.'},
      {night:2, theme:'The lightness of laughing at yourself', prompt:'The story wanders into the territory of self-directed laughter — the stumble, the ridiculousness, the way everything loosens when seriousness drops away. The lightness as landscape.'},
      {night:3, theme:'The sound of someone else\'s smile', prompt:'The story explores what it feels like to cause joy in another person — the spark, the contagion, the way a giggle moves from body to body like warmth.'},
      {night:4, theme:'Joy that exists alongside the rain', prompt:'The story sits inside a moment where things have gone wrong and joy is there anyway — not denying the rain, not explaining it away, just dancing in it. Joy as territory within difficulty.'},
      {night:5, theme:'The ceremony of small victories', prompt:'The story explores the feeling of celebrating something tiny — the private triumph, the quiet fist-pump, the way honouring a small win makes it real.'},
      {night:6, theme:'The delight of the attempt', prompt:'The story wanders into the territory of trying something purely for the trying — the fumbling, the aliveness, the way the doing itself is where the joy lives, separate from any result.'},
      {night:7, theme:'The warmth you leave in a room', prompt:'The story lives in the territory of joy\'s afterglow — the way one person\'s delight lingers in a space after they\'ve left. Not a moral about spreading happiness. The warmth itself, observed.'},
    ],
    dailyWisdom:[
      "I bet there's something fun hiding in today. Let's find it!",
      "Did something silly happen? Good. Silly is underrated.",
      "You know what's free and unlimited? Making someone smile.",
      "It's raining? PERFECT. Do you know how fun rain is?",
      "You did a thing today. Even a small thing. Let's celebrate!",
      "The best part of trying isn't winning. It's the trying part.",
      "Your happiness is contagious. Did you know that?",
    ],
  },
  {
    id:'otter', name:'River Otter', emoji:'🦦', color:'#C8A878',
    description:'playful, curious, loves everything',
    nameSuggestions:['Pebble','Kelp','Ripple','Dew'],
    virtue:'Friendship', craft:'constellation', craftName:'The Otter', craftEmoji:'✦',
    constellationPoints:[[15,40],[30,20],[50,15],[70,20],[85,40],[70,65],[35,65]],
    storyPersonality:'Playful and social. Can\'t sit still. Drags friends into adventures. But also: listens carefully, remembers what you said yesterday, and always saves you the good rock. Shows friendship through action.',
    virtueKeywords:['friendship','friends','sharing','together','teamwork','cooperation','playing','inclusion'],
    lessonBeats:[
      {night:1, theme:'The bravery of hello', prompt:'The story explores the tiny, enormous act of speaking first — the held breath before the word, the bridge that a single greeting builds across the space between two people.'},
      {night:2, theme:'Listening that remembers', prompt:'The story wanders into the territory of deep listening — what it feels like to be heard so carefully that a small detail is kept, and what that keeping means when it surfaces later.'},
      {night:3, theme:'The way sharing changes the thing', prompt:'The story explores how a beloved thing transforms when it\'s offered to someone else — the way sharing doesn\'t divide but somehow multiplies. The alchemy of togetherness.'},
      {night:4, theme:'The space between disagreeing and leaving', prompt:'The story sits inside a disagreement between friends — not the resolution, but the territory of staying through it. The friction, the hurt, the way back that doesn\'t require anyone to lose.'},
      {night:5, theme:'Presence on the hard days', prompt:'The story explores what it feels like to show up when there\'s nothing to fix — the silence that helps, the shoulder that\'s enough, the way being-there is its own language.'},
      {night:6, theme:'The circle getting wider', prompt:'The story wanders into the feeling of making room — what happens when the edge of a group opens to let someone in. The expansion, not the lesson about inclusion.'},
      {night:7, theme:'More yourself because of them', prompt:'The story lives in the territory of friendship\'s deepest work — the way the right people don\'t change you but somehow help you become more of what you already were. Not a revelation. A settling.'},
    ],
    dailyWisdom:[
      "Someone near you could use a 'hello' today. You could be the one.",
      "When your friend talks, listen with your whole face. They can tell.",
      "The best things are better when you share them with someone.",
      "Friends don't always agree. That's normal. You figure it out.",
      "Sometimes just sitting next to someone is the best thing you can do.",
      "There's always room for one more. Always.",
      "Your friends don't make you different. They make you more you.",
    ],
  },
  {
    id:'penguin', name:'Ice Penguin', emoji:'🐧', color:'#A0C8E0',
    description:'waddly, funny, surprisingly brave',
    nameSuggestions:['Pebble','Floe','Blizzard','Nook'],
    virtue:'Honesty', craft:'constellation', craftName:'The Penguin', craftEmoji:'✦',
    constellationPoints:[[50,10],[35,25],[65,25],[30,50],[70,50],[40,78],[60,78]],
    storyPersonality:'Awkward, honest to a fault, accidentally funny. Says what everyone is thinking. Not mean — just transparent. Shows that honesty is brave and sometimes uncomfortable but always builds trust.',
    virtueKeywords:['honesty','honest','truth','telling the truth','trust','integrity','sincere'],
    lessonBeats:[
      {night:1, theme:'What truth feels like in the body', prompt:'The story explores the physical sensation of truth versus untruth — the weight difference, the way truth sits lighter even when it\'s harder to carry. The body\'s landscape of honesty.'},
      {night:2, theme:'A hard thing said softly', prompt:'The story wanders into the territory of difficult truths delivered with care — the gentleness required, the way kindness and honesty can share the same breath. The tenderness of it.'},
      {night:3, theme:'The mirror you keep turning away from', prompt:'The story explores the territory of self-honesty — the thing you\'ve been avoiding admitting to yourself, what it feels like when you finally hold still and look. The looking, not the lesson.'},
      {night:4, theme:'What honesty costs', prompt:'The story sits inside the loss that sometimes follows truth-telling — the thing that leaves, the emptiness, and then the strange solidity of what remains. The cost as territory.'},
      {night:5, theme:'The foundation that truth builds', prompt:'The story explores the feeling of being trusted — the accumulated weight of consistent honesty, the way it builds something between people that can hold weight. The architecture of trust.'},
      {night:6, theme:'The shape of a half-truth', prompt:'The story wanders into the territory of partial honesty — the way a thing half-said can distort more than silence, the uncomfortable space between enough truth and all of it.'},
      {night:7, theme:'The lightness after', prompt:'The story lives in the territory that opens after honesty — the exhale, the spaciousness, the feeling of being unburdened. Not a lesson about freedom. The lightness itself, inhabited.'},
    ],
    dailyWisdom:[
      "Truth feels different in your body. Like putting something down.",
      "You can say a hard thing and still say it softly.",
      "The hardest person to be honest with is yourself.",
      "Telling the truth sometimes costs. It's still worth it.",
      "People trust you because you tell the truth. Even the tricky parts.",
      "A half-truth is a whole problem. Say all of it.",
      "After you tell the truth, notice how much lighter you feel.",
    ],
  },
  {
    id:'hedgehog', name:'Glow Hog', emoji:'🦔', color:'#D4A878',
    description:'shy at first, heart of gold',
    nameSuggestions:['Prickle','Bramble','Acorn','Noodle'],
    virtue:'Vulnerability', craft:'constellation', craftName:'The Hedgehog', craftEmoji:'✦',
    constellationPoints:[[50,15],[30,20],[70,20],[20,45],[80,45],[35,72],[65,72]],
    storyPersonality:'Curls up in a ball when scared. Prickly outside, impossibly soft inside. Slowly unfurls as trust builds. Shows that letting people in — despite the risk — is the bravest thing of all.',
    virtueKeywords:['vulnerability','feelings','emotions','opening up','trust','sensitivity','shy','sensitive'],
    lessonBeats:[
      {night:1, theme:'The double life of walls', prompt:'The story explores the territory of protection that is also isolation — the warmth of the shell and the loneliness inside it, held together. Not a lesson about opening up. The paradox itself.'},
      {night:2, theme:'The enormity of one small opening', prompt:'The story wanders into the feeling of letting one person in — just one — the size of that tiny crack, the way it feels both terrifying and enormous. The opening as landscape.'},
      {night:3, theme:'What a feeling looks like when it\'s let out', prompt:'The story explores the moment a feeling surfaces — the way sadness or fear or love changes shape when it\'s spoken. Not weakness corrected. The feeling itself, given air.'},
      {night:4, theme:'The sound of asking out loud', prompt:'The story sits inside the act of saying what you need — the vulnerability of the request, the way it feels to stop hinting and actually speak the thing. The asking is the territory.'},
      {night:5, theme:'Being seen, all of it', prompt:'The story explores the territory of showing the real, unedited self — the quirks, the mess, the specificity — and what the air feels like when acceptance arrives. The showing, not the moral.'},
      {night:6, theme:'The survivability of being let down', prompt:'The story wanders into the landscape of vulnerability that meets disappointment — the sting, the instinct to close, and then the quiet fact of still being here. The surviving as territory.'},
      {night:7, theme:'Choosing open, again', prompt:'The story lives in the territory of staying soft after being hurt — the ongoing choice of openness, not once but again. Not a triumph. A daily, quiet, extraordinary act.'},
    ],
    dailyWisdom:[
      "Your walls keep you safe. But they also keep you alone.",
      "You don't have to open up to everyone. Just one person is enough.",
      "Feelings aren't weakness. They're the bravest part of you.",
      "You're allowed to say what you need. Out loud.",
      "The real you — the weird, messy, specific you — that's the loveable one.",
      "Someone might let you down. You'll survive. You always do.",
      "Staying open after being hurt? That's the strongest thing there is.",
    ],
  },
  {
    id:'lion', name:'Sun Lion', emoji:'🦁', color:'#F0B840',
    description:'born to lead, loves cuddles secretly',
    nameSuggestions:['Soleil','Mane','Kibo','Zuri'],
    virtue:'Leadership', craft:'constellation', craftName:'The Lion', craftEmoji:'✦',
    constellationPoints:[[50,8],[25,25],[75,25],[15,50],[85,50],[30,78],[70,78]],
    storyPersonality:'Confident but not arrogant. Leads by doing, not telling. Secretly needs reassurance. Shows that real leadership is service — going first so others feel safe to follow.',
    virtueKeywords:['leadership','leader','responsibility','taking charge','brave','standing up','confidence'],
    lessonBeats:[
      {night:1, theme:'The feeling of going first', prompt:'The story explores what it feels like to step forward when no one else has — the fear, the loneliness, the way the first step changes the shape of the space for everyone behind you.'},
      {night:2, theme:'The strength inside listening', prompt:'The story wanders into the territory of changing your mind because someone else saw better — what it feels like to let go of your plan, the surprising strength in the release.'},
      {night:3, theme:'The weight of "that was me"', prompt:'The story explores the landscape of taking responsibility — the heaviness of it, the way it lands in the room, the strange relief that follows the admission. The owning as territory.'},
      {night:4, theme:'Stepping back so someone can step forward', prompt:'The story sits inside the act of making room — the feeling of shrinking yourself so another person can grow. Not selflessness as lesson. The particular warmth of watching someone else shine.'},
      {night:5, theme:'The leader who says "I\'m struggling"', prompt:'The story explores the territory of admitting you can\'t carry it all — the vulnerability at the front of the line, the way asking for help changes the shape of leadership.'},
      {night:6, theme:'The decision that costs you something', prompt:'The story wanders into the territory of hard choices — the kind where what\'s right for everyone is not what\'s easy for you. The choosing as landscape, not a moral about sacrifice.'},
      {night:7, theme:'Leading by being gentle', prompt:'The story lives in the territory of quiet leadership — kindness as direction, example as instruction. Not a lesson about leading well. The gentle authority of someone who simply goes first, softly.'},
    ],
    dailyWisdom:[
      "Someone has to go first. Why not you?",
      "The best leaders don't talk the most. They listen the most.",
      "When things go wrong, the leader says 'that was me' — even when it wasn't.",
      "Making someone else look good? That's what leaders actually do.",
      "Even leaders need someone. Especially leaders.",
      "The right thing and the easy thing are usually different things.",
      "The strongest way to lead is by being kind. Always.",
    ],
  },
  {
    id:'turtle', name:'Tide Turtle', emoji:'🐢', color:'#88C8A0',
    description:'old soul, patient, full of wisdom',
    nameSuggestions:['Coral','Tide','Mossy','Shelly'],
    virtue:'Empathy', craft:'constellation', craftName:'The Turtle', craftEmoji:'✦',
    constellationPoints:[[40,15],[60,15],[75,35],[70,60],[50,75],[30,60],[25,35]],
    storyPersonality:'Old soul. Moves slowly but sees deeply. Feels what others feel. Carries the stories of everyone they\'ve met. Shows empathy not as a skill but as a way of being in the world.',
    virtueKeywords:['empathy','understanding others','feelings','perspective','compassion','walking in shoes','seeing others'],
    lessonBeats:[
      {night:1, theme:'The whole life you didn\'t see', prompt:'The story explores the moment assumptions crumble — the disorientation of finding out someone\'s story is nothing like what you imagined. The gap between assumption and truth as territory.'},
      {night:2, theme:'Wearing someone else\'s weather', prompt:'The story wanders into the landscape of imagining yourself inside another person\'s life — what their days feel like, the weight they carry, the way the imagining changes something in your own body.'},
      {night:3, theme:'Where words land versus where they were thrown', prompt:'The story explores the space between intention and impact — the surprise of a word arriving somewhere you didn\'t aim it, the way the same sentence can mean different things depending on who catches it.'},
      {night:4, theme:'Sitting in someone else\'s sadness', prompt:'The story sits inside the act of not-fixing — being beside someone in their pain, offering nothing but presence. The discomfort of it, the sufficiency of it. The sitting as landscape.'},
      {night:5, theme:'Happiness for someone else\'s happiness', prompt:'The story explores the complicated territory of feeling glad for another person\'s good fortune — the genuine warmth of it, even when it brushes against your own wanting. The generosity of shared joy.'},
      {night:6, theme:'Understanding without agreeing', prompt:'The story wanders into the territory of comprehending why someone did a hurtful thing — holding the understanding and the boundary at the same time. Empathy that doesn\'t erase the line.'},
      {night:7, theme:'The wordless bridge', prompt:'The story lives in a moment of understanding that needs no language — two people recognising something in each other, across whatever divides them. Not a lesson about connection. The connection itself.'},
    ],
    dailyWisdom:[
      "That person who annoyed you today? They have a whole life you don't know about.",
      "Before you decide what to say, imagine hearing it.",
      "The same words can feel totally different to someone else.",
      "Sometimes people don't need you to fix it. They need you to sit with it.",
      "Being happy for someone else is one of the hardest, best things.",
      "You can understand someone without agreeing with them.",
      "We're all just walking each other home.",
    ],
  },
  {
    id:'elephant', name:'Cloud Elephant', emoji:'🐘', color:'#B0C8E0',
    description:'big-hearted, never forgets a friend',
    nameSuggestions:['Nimbus','Cinder','Petal','Rogue'],
    virtue:'Generosity', craft:'constellation', craftName:'The Elephant', craftEmoji:'✦',
    constellationPoints:[[30,15],[55,10],[75,20],[80,45],[65,70],[40,75],[20,50]],
    storyPersonality:'Enormous heart. Gives without thinking. Carries others when they\'re tired. Shows that generosity isn\'t about having a lot — it\'s about sharing whatever you have.',
    virtueKeywords:['generosity','generous','giving','sharing','selfless','helping others','charity'],
    lessonBeats:[
      {night:1, theme:'The impulse to give', prompt:'The story explores the first stirring of generosity — the moment before the hand opens, the pull toward sharing something you have with someone who needs it. The impulse as landscape.'},
      {night:2, theme:'The gift of unhurried attention', prompt:'The story wanders into the territory of giving time — the way undivided attention feels to both giver and receiver, the warmth of being fully present. Time as the most valuable offering.'},
      {night:3, theme:'Giving with open hands', prompt:'The story explores the feeling of offering something with no expectation of return — the purity of it, the way it changes the giver. Not a lesson about selflessness. The open-handedness itself.'},
      {night:4, theme:'Generosity from almost-empty', prompt:'The story sits inside the act of giving when you have very little — the way generosity feels different when it costs more, the territory of sharing from scarcity rather than abundance.'},
      {night:5, theme:'The strange difficulty of accepting', prompt:'The story explores the territory of receiving — the awkwardness, the instinct to refuse, the way letting someone be generous to you requires its own kind of openness.'},
      {night:6, theme:'The mathematics of sharing', prompt:'The story wanders into the paradox of things that multiply when divided — the way sharing defies subtraction, the strange arithmetic of giving and having more. The paradox as territory.'},
      {night:7, theme:'Fuller after giving', prompt:'The story lives in the territory of the full heart — the feeling of being more after giving, not less. Not a lesson about generosity\'s rewards. The inexplicable fullness, rested inside.'},
    ],
    dailyWisdom:[
      "You always have something to give. Always.",
      "The best gift isn't a thing. It's your time.",
      "Give it. Don't count. Don't wait for thank you.",
      "You don't need a lot to give a lot.",
      "Someone gave you something today. Did you let yourself receive it?",
      "When you share, you don't have less. You have more.",
      "A heart that gives is a heart that's full.",
    ],
  },
  {
    id:'axolotl', name:'Star Axolotl', emoji:'🐠', color:'#F09898',
    description:'the rarest find, uniquely magical',
    nameSuggestions:['Lotl','Gilly','Bloop','Frilly'],
    virtue:'Self-acceptance', craft:'constellation', craftName:'The Axolotl', craftEmoji:'✦',
    constellationPoints:[[25,30],[40,10],[60,10],[75,30],[70,55],[50,75],[30,55]],
    storyPersonality:'Wonderfully weird. Knows they\'re different and has made peace with it. Not trying to fit in — but not trying to stand out either. Just fully, unapologetically themselves.',
    virtueKeywords:['self-acceptance','accepting yourself','being different','unique','weird','self-love','identity'],
    lessonBeats:[
      {night:1, theme:'The fact of being different', prompt:'The story explores the plain reality of being unlike others — not as a problem or a gift, just as a fact. The shape of difference observed without judgement. The territory of simply being what you are.'},
      {night:2, theme:'The trap of measuring yourself against others', prompt:'The story wanders into the landscape of comparison — the exhaustion of it, the way it shrinks you, the moment of stepping off that treadmill. Not a lesson about self-worth. The stepping-off itself.'},
      {night:3, theme:'The strange usefulness of your particular shape', prompt:'The story explores the moment when the odd thing about you turns out to fit perfectly somewhere — not as vindication, but as the quiet satisfaction of a key meeting its lock.'},
      {night:4, theme:'Being misunderstood and still being whole', prompt:'The story sits inside the experience of not being gotten — the loneliness of it, and then the surprising sturdiness of being okay anyway. The okayness as territory.'},
      {night:5, theme:'The feeling of being recognised', prompt:'The story explores what it feels like to meet someone who sees you clearly — the relief, the homecoming, the way recognition changes the temperature. The finding, not the lesson about belonging.'},
      {night:6, theme:'Changing because you want to', prompt:'The story wanders into the territory of self-chosen change — the difference between shifting because someone asked and shifting because something in you wanted to. Agency as landscape.'},
      {night:7, theme:'Looking at yourself and staying', prompt:'The story lives in the territory of self-regard — the act of looking at all of yourself and not flinching, not wishing. The plain, quiet sufficiency of being exactly this. Not a declaration. A settling.'},
    ],
    dailyWisdom:[
      "You're different. That's not a problem. That's the point.",
      "Comparing yourself to someone else is like comparing the moon to a lamp. Why?",
      "That weird thing about you? It's your superpower. Give it time.",
      "Not everyone will get you. That's fine. You're not for everyone.",
      "Somewhere out there is someone who thinks exactly like you. You'll find them.",
      "If you're going to change, change because you want to. Nobody else gets a vote.",
      "Look at yourself. Really look. You were always enough.",
    ],
  },
  {
    id:'koala', name:'Gum Koala', emoji:'🐨', color:'#B0C0D0',
    description:'peaceful, expert napper, dreamy',
    nameSuggestions:['Euca','Snoozy','Foggy','Bluegum'],
    virtue:'Peace', craft:'constellation', craftName:'The Koala', craftEmoji:'✦',
    constellationPoints:[[40,12],[60,12],[25,35],[75,35],[35,62],[65,62],[50,82]],
    storyPersonality:'The calmest presence in any story. Not passive — peacefully certain. When chaos erupts, they\'re the still point. Shows that peace is not the absence of trouble — it\'s the choice not to add to it.',
    virtueKeywords:['peace','peaceful','calm','serenity','conflict resolution','harmony','stillness','mindfulness'],
    lessonBeats:[
      {night:1, theme:'The stillness at the centre', prompt:'The story explores what it feels like to be the calm point while everything swirls — the weight of stillness, the way it radiates outward. Not a lesson about staying calm. The stillness itself as landscape.'},
      {night:2, theme:'The choice not to add', prompt:'The story wanders into the territory of restraint — the moment of choosing not to react, the held breath, the space that opens when fuel is withheld from a fire. The not-adding as territory.'},
      {night:3, theme:'The quiet place inside', prompt:'The story explores the inner landscape of calm — a real, inhabitable space that exists somewhere behind the noise. The building of it, the furnishing of it, the way it waits for you.'},
      {night:4, theme:'The strength peace requires', prompt:'The story sits inside the difficulty of choosing peace — the effort it takes, the way fighting would be easier, the particular bravery of softness in a hard moment. Peace as an active, muscular choice.'},
      {night:5, theme:'Helping two people hear each other', prompt:'The story explores the territory between two people in conflict — the bridge-building, the translating, the way peace happens when both sides feel heard. Not conflict resolution. The hearing as landscape.'},
      {night:6, theme:'Weather that passes through you', prompt:'The story wanders into the landscape of inner turmoil — anger, anxiety, the storm of feeling — and the slow, observing act of watching it move through without holding on. The passing as territory.'},
      {night:7, theme:'The lantern you carry', prompt:'The story lives in the territory of portable peace — the calm that goes with you, that enters rooms before you do, that steadies the air. Not a gift described. A presence inhabited.'},
    ],
    dailyWisdom:[
      "When everyone is loud, the quiet one changes everything.",
      "You don't have to react. You get to choose.",
      "Close your eyes. You have a quiet place inside. It's always there.",
      "Choosing peace when you could fight? That takes more strength.",
      "You can't make people agree. But you can make them feel heard.",
      "That big feeling you have right now? Watch it. It's going to pass.",
      "You carry peace with you wherever you go. Like a light.",
    ],
  },
  {
    id:'hummingbird', name:'Bloom Bird', emoji:'🐦', color:'#F080A0',
    description:'lightning-fast, tiny heart, pure joy',
    nameSuggestions:['Zinnia','Flutter','Nectar','Jewel'],
    virtue:'Curiosity', craft:'constellation', craftName:'The Hummingbird', craftEmoji:'✦',
    constellationPoints:[[20,35],[35,15],[55,10],[75,20],[80,45],[60,65],[40,55]],
    storyPersonality:'Can\'t stop moving. Fascinated by everything. Asks questions faster than anyone can answer. Not scattered — intensely focused on whatever has caught their attention right now. Shows that curiosity is the root of all learning.',
    virtueKeywords:['curiosity','curious','questions','exploring','learning','discovering','wonder','adventurous'],
    lessonBeats:[
      {night:1, theme:'The question that was sitting there all along', prompt:'The story explores the feeling of asking what nobody thought to ask — the way a question can change the shape of a room. Not a lesson about curiosity. The question itself, and the space it opens.'},
      {night:2, theme:'Where a thread goes when you follow it', prompt:'The story wanders along a single thread of curiosity — the unexpected turns, the widening world, the way one small wonder leads somewhere no map predicted. The following as landscape.'},
      {night:3, theme:'The aliveness of the first time', prompt:'The story explores the particular feeling of doing something for the first time — the newness, the not-knowing-how, the way wonder and clumsiness share the same moment. The trying as territory.'},
      {night:4, theme:'The interesting wreckage of a wrong guess', prompt:'The story sits inside the territory of being wrong — the surprise of it, the way a mistake opens a door the right answer would have walked past. The wrongness as unexpected landscape.'},
      {night:5, theme:'Curiosity turned toward a person', prompt:'The story explores what happens when curiosity is aimed at another human being — their story, their inner weather, the way wondering about someone deepens the space between you.'},
      {night:6, theme:'The pleasure of not knowing', prompt:'The story wanders into the territory of mystery that stays mysterious — the delight of a thing that can\'t be explained, the way wonder thrives in the space where answers would only shrink it.'},
      {night:7, theme:'The question that opens into the next question', prompt:'The story lives in the territory of unending curiosity — the way one question blooms into another, and another. Not a conclusion about the importance of asking. The asking itself, multiplying.'},
    ],
    dailyWisdom:[
      "What's a question nobody asked today? Ask it.",
      "Follow the thing that interests you. It knows where to go.",
      "You've never done that before? Perfect. Let's try it.",
      "Wrong answers are just right answers to a different question.",
      "Be as curious about people as you are about everything else.",
      "Not everything needs an answer. Some things are better as questions.",
      "The best people never stop asking why.",
    ],
  },
];

export const getCreature = (id: string): CreatureDef =>
  CREATURES.find(c => c.id === id) ?? CREATURES[0];

export const getCreatureByVirtueKeyword = (keyword: string): CreatureDef | null => {
  const lower = keyword.toLowerCase();
  return CREATURES.find(c => c.virtueKeywords.some(k => lower.includes(k))) ?? null;
};

export const getCreatureByVirtue = (virtue: string): CreatureDef | null => {
  const lower = virtue.toLowerCase();
  return CREATURES.find(c => c.virtue.toLowerCase() === lower) ?? null;
};
