export interface LessonBeat {
  night: number;
  theme: string;       // short label for the completion card
  prompt: string;      // injected into story generation prompt
}

export interface CreatureDef {
  id: string;
  name: string;
  emoji: string;
  color: string;
  description: string;
  nameSuggestions: string[];
  // Dreamkeeper system
  virtue: string;              // the moral theme this creature teaches
  craft: string;               // always 'constellation'
  craftName: string;           // unique constellation name (e.g. 'The Bunny')
  craftEmoji: string;          // always '✦'
  storyPersonality: string;    // how the creature behaves in stories (for AI prompt)
  virtueKeywords: string[];    // maps story lessons to this creature
  // Constellation — 7 star positions in a ~100x100 viewBox
  constellationPoints: [number,number][];
  lessonBeats: LessonBeat[];   // 7 progressive lessons
  dailyWisdom: string[];       // 7 homepage speech lines (indexed by egg night)
}

export const CREATURES: CreatureDef[] = [
  {
    id:'bunny', name:'Moon Bunny', emoji:'🐰', color:'#F5B84C',
    description:'soft, moonlit, impossibly fluffy',
    nameSuggestions:['Luna','Mochi','Pip','Star'],
    virtue:'Courage', craft:'constellation', craftName:'The Bunny', craftEmoji:'✦',
    constellationPoints:[[35,5],[30,30],[50,38],[70,30],[65,5],[40,60],[60,60]],
    storyPersonality:'Timid but willing to try. Speaks in short, warm sentences. Hides behind the hero at first but steps forward when it matters. Models courage through small quiet acts rather than big dramatic ones.',
    virtueKeywords:['courage','bravery','brave','fear','facing fears','scared','afraid'],
    lessonBeats:[
      {night:1, theme:'Being scared is okay', prompt:'The story should feature a moment where the hero or their companion notices they feel afraid — and that feeling is treated as normal and valid, not something to fix.'},
      {night:2, theme:'Name what frightens you', prompt:'The story should include a moment where a character names their fear out loud, and the act of naming it makes it feel slightly smaller.'},
      {night:3, theme:'One small step is enough', prompt:'The story should show the hero taking one tiny brave action — not a grand gesture, just one step toward the thing that scares them.'},
      {night:4, theme:'Falling means you tried', prompt:'The hero should try something brave, fail at it, and discover that the failing itself was brave — because they tried.'},
      {night:5, theme:'Help others find their brave', prompt:'The hero should notice someone else who is scared and help them feel braver — modelling courage through encouragement.'},
      {night:6, theme:'You were ready all along', prompt:'The hero faces a real challenge and discovers they had the courage inside them the whole time — it was built from all the small steps before.'},
      {night:7, theme:'Courage is quiet', prompt:'The story should end with a moment of quiet, everyday courage — not a dramatic victory, but a small choice to stay, to speak, or to try again tomorrow.'},
    ],
    dailyWisdom:[
      "Did you know? Being scared and being brave are the same feeling.",
      "If you can name the scary thing, it gets a little smaller. Try it.",
      "You don't have to jump. You just have to step.",
      "The bravest people aren't the ones who never fall.",
      "Know what's really brave? Helping someone else try.",
      "You've been ready for this longer than you think.",
      "Courage isn't loud. Sometimes it's just staying.",
    ],
  },
  {
    id:'fox', name:'Ember Fox', emoji:'🦊', color:'#FF8264',
    description:'clever, warm, a little mischievous',
    nameSuggestions:['Ember','Russet','Maple','Blaze'],
    virtue:'Cleverness', craft:'constellation', craftName:'The Fox', craftEmoji:'✦',
    constellationPoints:[[20,30],[35,15],[55,20],[75,10],[80,35],[65,55],[45,70]],
    storyPersonality:'Quick-witted and playful. Sees solutions others miss. Sometimes too clever for their own good. Learns that the smartest answer isn\'t always the trickiest one.',
    virtueKeywords:['cleverness','clever','problem solving','thinking','smart','creative thinking','wit'],
    lessonBeats:[
      {night:1, theme:'Look closer', prompt:'The story should feature a moment where something obvious is missed because nobody looked carefully enough — until someone does.'},
      {night:2, theme:'Ask why', prompt:'A character should solve a small problem by asking "why" instead of accepting things as they are.'},
      {night:3, theme:'Try a different way', prompt:'The hero should face a problem that can\'t be solved the obvious way and discover an unexpected approach.'},
      {night:4, theme:'Mistakes teach', prompt:'The hero\'s clever plan should backfire — but the mistake itself reveals something important.'},
      {night:5, theme:'Two heads think better', prompt:'The hero should solve a problem by combining their idea with someone else\'s — showing that collaboration beats solo cleverness.'},
      {night:6, theme:'The simple answer', prompt:'After trying complicated solutions, the hero should discover that the simplest answer was the right one all along.'},
      {night:7, theme:'Wisdom over tricks', prompt:'The story should end with the hero choosing the wise path over the clever trick — showing that real intelligence includes knowing when not to be clever.'},
    ],
    dailyWisdom:[
      "The best answers are hiding in the places nobody thinks to look.",
      "Why? is the most powerful word you'll ever learn.",
      "When the door is locked, check the window.",
      "Every mistake is a clue in disguise.",
      "Your idea plus their idea makes a better idea.",
      "Sometimes the answer is so simple you almost miss it.",
      "Being clever is good. Being wise is better.",
    ],
  },
  {
    id:'dragon', name:'Storm Drake', emoji:'🐉', color:'#60C8A0',
    description:'fierce, magical, secretly gentle',
    nameSuggestions:['Zephyr','Sprig','Kite','Ember'],
    virtue:'Resilience', craft:'constellation', craftName:'The Dragon', craftEmoji:'✦',
    constellationPoints:[[15,50],[30,25],[50,15],[70,20],[85,40],[70,65],[40,75]],
    storyPersonality:'Fierce on the outside, surprisingly tender. Gets knocked down a lot. Always gets back up. Has a quiet stubbornness that looks like strength. Never gives a speech about resilience — just does it.',
    virtueKeywords:['resilience','perseverance','never giving up','persistence','tough','bouncing back','grit','determination'],
    lessonBeats:[
      {night:1, theme:'Hard things happen', prompt:'The story should honestly acknowledge that something difficult has happened — without rushing to fix it.'},
      {night:2, theme:'It\'s okay to feel it', prompt:'A character should sit with a difficult feeling instead of pushing it away — sadness, frustration, or disappointment treated as valid.'},
      {night:3, theme:'One more try', prompt:'The hero should try again after failing — not because they\'re sure it will work, but because giving up doesn\'t feel right either.'},
      {night:4, theme:'Rest is not quitting', prompt:'The hero should choose to pause, rest, and recover — and the story should show this as strength, not weakness.'},
      {night:5, theme:'Lean on someone', prompt:'The hero should accept help from someone — showing that resilience includes knowing when you need others.'},
      {night:6, theme:'Stronger at the broken places', prompt:'The hero should discover that something that broke and was repaired is now stronger or more beautiful than before.'},
      {night:7, theme:'Tomorrow is new', prompt:'The story should end with a quiet sense that tomorrow exists, and that\'s enough — not everything is solved, but the hero will be there for it.'},
    ],
    dailyWisdom:[
      "Hard things happen. That part isn't your fault.",
      "You don't have to be okay right now. Just be here.",
      "One more try doesn't mean you're not tired. It means you're brave.",
      "Resting isn't giving up. It's getting ready.",
      "Even dragons ask for help sometimes.",
      "Broken things that heal are stronger than things that never broke.",
      "Tomorrow is a whole new sky.",
    ],
  },
  {
    id:'owl', name:'Dusk Owl', emoji:'🦉', color:'#9A7FD4',
    description:'wise, watchful, full of secrets',
    nameSuggestions:['Sage','Dusk','Merlin','Hoot'],
    virtue:'Wisdom', craft:'constellation', craftName:'The Owl', craftEmoji:'✦',
    constellationPoints:[[50,10],[30,30],[70,30],[25,55],[75,55],[40,80],[60,80]],
    storyPersonality:'Quiet observer who notices everything. Speaks rarely but every word matters. Never tells the hero what to do — asks questions that help them figure it out themselves.',
    virtueKeywords:['wisdom','wise','choices','decisions','thinking before acting','judgement','understanding'],
    lessonBeats:[
      {night:1, theme:'Stop and notice', prompt:'The hero should pause in the middle of action and notice something everyone else missed.'},
      {night:2, theme:'Listen before speaking', prompt:'A character should solve a problem by listening carefully instead of talking.'},
      {night:3, theme:'Not everything is what it seems', prompt:'Something in the story should turn out to be different from how it first appeared.'},
      {night:4, theme:'Think about tomorrow', prompt:'The hero should make a choice that\'s harder now but better later — delayed gratification shown through story.'},
      {night:5, theme:'Everyone knows something', prompt:'The hero should learn something important from an unlikely or unexpected teacher.'},
      {night:6, theme:'The question matters more', prompt:'The hero should discover that asking the right question was more important than finding the answer.'},
      {night:7, theme:'Knowing what you don\'t know', prompt:'The story should end with the hero comfortable with uncertainty — wise enough to say "I don\'t know" and mean it peacefully.'},
    ],
    dailyWisdom:[
      "The world tells you things all day. Most people forget to listen.",
      "Your ears are older than your mouth. Use them first.",
      "Things aren't always what they look like from here.",
      "The easy choice and the right choice are rarely the same.",
      "Everyone you meet knows something you don't.",
      "A good question is worth more than a quick answer.",
      "The wisest words in any language: I don't know yet.",
    ],
  },
  {
    id:'bear', name:'Frost Bear', emoji:'🐻', color:'#90C8E8',
    description:'cosy, strong, warmth itself',
    nameSuggestions:['Frost','Birch','Cloud','Pudding'],
    virtue:'Kindness', craft:'constellation', craftName:'The Bear', craftEmoji:'✦',
    constellationPoints:[[35,15],[65,15],[20,40],[80,40],[50,50],[30,78],[70,78]],
    storyPersonality:'Warm, gentle, and solid. Gives the best hugs in any story. Notices when someone is cold, hungry, or lonely before anyone else does. Kindness is automatic, not performed.',
    virtueKeywords:['kindness','kind','caring','compassion','helping','empathy','gentle','thoughtful'],
    lessonBeats:[
      {night:1, theme:'Notice who needs help', prompt:'The hero should notice someone who needs something — not because they asked, but because the hero was paying attention.'},
      {night:2, theme:'Small things matter', prompt:'A tiny act of kindness should have an unexpectedly large impact on someone else.'},
      {night:3, theme:'Kindness to yourself', prompt:'The hero should learn to be kind to themselves — forgiving a mistake or taking care of their own needs.'},
      {night:4, theme:'When kindness is hard', prompt:'The hero should be kind to someone who hasn\'t been kind to them — and it should feel difficult but right.'},
      {night:5, theme:'Kindness without credit', prompt:'The hero should do something kind that nobody else sees or knows about — kindness for its own sake.'},
      {night:6, theme:'Receiving kindness', prompt:'The hero should struggle to accept help or kindness from someone else — and learn that receiving is also generous.'},
      {night:7, theme:'Kindness ripples', prompt:'The story should end showing how one kind act set off a chain of kindness through other characters — without the hero knowing.'},
    ],
    dailyWisdom:[
      "Look around. Someone near you could use a friend right now.",
      "The smallest things you do are sometimes the biggest things to someone else.",
      "Be as kind to yourself as you are to your favourite person.",
      "Being kind to someone who wasn't kind to you? That's the real thing.",
      "The best kind things are the ones nobody sees.",
      "Letting someone help you is a gift to them too.",
      "One kind thing becomes a hundred kind things. You just don't see them all.",
    ],
  },
  {
    id:'cat', name:'Shadow Cat', emoji:'🐱', color:'#A090D0',
    description:'curious, independent, secretly snuggly',
    nameSuggestions:['Misty','Nimbus','Pixel','Wisp'],
    virtue:'Independence', craft:'constellation', craftName:'The Cat', craftEmoji:'✦',
    constellationPoints:[[25,20],[45,10],[65,15],[80,30],[70,55],[50,75],[30,60]],
    storyPersonality:'Walks their own path. Comfortable being different. Not rebellious — just quietly certain. Shows that independence means knowing who you are, not pushing others away.',
    virtueKeywords:['independence','confident','self-belief','being yourself','different','unique','standing alone'],
    lessonBeats:[
      {night:1, theme:'You don\'t have to follow', prompt:'The hero should choose to go a different direction from everyone else — and it should feel uncertain but honest.'},
      {night:2, theme:'Your way is valid', prompt:'The hero\'s unusual approach to something should turn out to work perfectly.'},
      {night:3, theme:'Alone isn\'t lonely', prompt:'The hero should spend time alone and discover it feels peaceful and full, not empty.'},
      {night:4, theme:'Say what you think', prompt:'The hero should express an opinion that\'s different from the group — respectfully but firmly.'},
      {night:5, theme:'Independence isn\'t isolation', prompt:'The hero should choose to come back to their friends after being independent — showing that independence includes choosing connection.'},
      {night:6, theme:'Trust yourself', prompt:'The hero should face a moment where everyone says one thing but their instinct says another — and they trust themselves.'},
      {night:7, theme:'Be all of who you are', prompt:'The story should end with the hero comfortable being their full, complex self — independent AND connected, strong AND soft.'},
    ],
    dailyWisdom:[
      "Just because everyone else is going that way doesn't mean you have to.",
      "Your way of doing things? It's not wrong. It's yours.",
      "Sometimes the best company is your own.",
      "It's okay to think something different. Say it gently and mean it.",
      "Being independent doesn't mean being alone. It means choosing.",
      "That feeling in your belly that says 'this way'? Trust it.",
      "You can be soft and strong. Quiet and brave. All of it. All at once.",
    ],
  },
  {
    id:'wolf', name:'Moon Wolf', emoji:'🐺', color:'#88B0D8',
    description:'loyal, fierce, runs with the stars',
    nameSuggestions:['Ash','Gale','Storm','Silver'],
    virtue:'Loyalty', craft:'constellation', craftName:'The Wolf', craftEmoji:'✦',
    constellationPoints:[[20,60],[35,35],[50,20],[70,15],[85,30],[75,55],[55,75]],
    storyPersonality:'Devoted and protective. Runs ahead to check the path is safe, then comes back. Shows loyalty through action — being there — not words. Has a quiet intensity.',
    virtueKeywords:['loyalty','loyal','trust','promise','showing up','reliable','dependable','commitment'],
    lessonBeats:[
      {night:1, theme:'Show up', prompt:'The hero should show up for someone simply by being there — no grand gesture, just presence.'},
      {night:2, theme:'Keep your word', prompt:'The hero should keep a promise even when it becomes inconvenient or difficult.'},
      {night:3, theme:'Stand by someone', prompt:'The hero should stand beside someone who is being treated unfairly — loyalty as solidarity.'},
      {night:4, theme:'Loyalty has limits', prompt:'The hero should learn that loyalty doesn\'t mean agreeing with everything — sometimes loyalty means saying "I think you\'re wrong, but I\'m still here."'},
      {night:5, theme:'Earn trust slowly', prompt:'The hero should earn someone\'s trust through consistent small actions over time, not one big moment.'},
      {night:6, theme:'Forgive and stay', prompt:'Someone should let the hero down, and the hero should choose to forgive and stay — showing that loyalty survives mistakes.'},
      {night:7, theme:'The pack remembers', prompt:'The story should end with the hero realising that their loyalty was noticed and remembered, even when they thought no one was watching.'},
    ],
    dailyWisdom:[
      "Sometimes the bravest thing is just showing up.",
      "A promise is a promise. Even the small ones.",
      "Standing next to someone when things are hard — that's everything.",
      "Real loyalty isn't agreeing. It's staying.",
      "Trust is built in tiny moments. Every single one counts.",
      "People make mistakes. Staying is a choice you make every time.",
      "The people who matter remember every time you showed up.",
    ],
  },
  {
    id:'unicorn', name:'Dream Unicorn', emoji:'🦄', color:'#E8A8D8',
    description:'magical, rare, makes wishes real',
    nameSuggestions:['Aurora','Shimmer','Opal','Celestia'],
    virtue:'Imagination', craft:'constellation', craftName:'The Unicorn', craftEmoji:'✦',
    constellationPoints:[[40,10],[55,5],[70,20],[75,45],[60,65],[40,70],[25,45]],
    storyPersonality:'Sees magic everywhere others see ordinary. Turns puddles into oceans and blankets into mountains. Not naive — genuinely creative. Shows that imagination is a superpower, not childishness.',
    virtueKeywords:['imagination','creative','creativity','wonder','dreaming','ideas','make-believe','pretend'],
    lessonBeats:[
      {night:1, theme:'See what isn\'t there yet', prompt:'The hero should imagine something that doesn\'t exist yet — and that imagining should be the first step toward making it real.'},
      {night:2, theme:'Boring things are secretly interesting', prompt:'The hero should find something magical in the most ordinary, everyday object or moment.'},
      {night:3, theme:'What if?', prompt:'The hero should ask "what if?" and follow that question somewhere completely unexpected.'},
      {night:4, theme:'Make something from nothing', prompt:'The hero should create something beautiful or useful from materials others would have thrown away.'},
      {night:5, theme:'Share your world', prompt:'The hero should invite someone else into their imaginary world — and that sharing should bring them closer.'},
      {night:6, theme:'Believe it first', prompt:'The hero should believe in something impossible — and that belief should be the thing that makes it possible.'},
      {night:7, theme:'The real magic is you', prompt:'The story should end with the hero realising that the magic wasn\'t in the wand or the spell — it was in the way they see the world.'},
    ],
    dailyWisdom:[
      "Close your eyes. What do you see? That's where we're going tonight.",
      "That boring thing in the corner? Look again. It's full of secrets.",
      "What if the sky was made of something else? What would you choose?",
      "You don't need fancy things. You need fancy ideas.",
      "The best worlds are the ones you share with someone.",
      "If you believe it hard enough, it starts to become real.",
      "The magic was never in the wand. It was in you the whole time.",
    ],
  },
  {
    id:'panda', name:'Cloud Panda', emoji:'🐼', color:'#B0A0D8',
    description:'gentle giant, nap champion',
    nameSuggestions:['Mochi','Bao','Nori','Snowdrop'],
    virtue:'Patience', craft:'constellation', craftName:'The Panda', craftEmoji:'✦',
    constellationPoints:[[35,15],[65,15],[20,40],[80,40],[35,65],[65,65],[50,85]],
    storyPersonality:'Calm, unhurried, and completely content to wait. Never rushes. Treats every moment as enough. Shows that patience isn\'t passive — it\'s choosing to trust that things take time.',
    virtueKeywords:['patience','patient','waiting','calm','peaceful','still','slow','mindful'],
    lessonBeats:[
      {night:1, theme:'Slow down', prompt:'The hero should be rushing and miss something important — then slow down and find it.'},
      {night:2, theme:'Wait for it', prompt:'Something good should come to the hero specifically because they waited instead of grabbing.'},
      {night:3, theme:'Breathe first', prompt:'The hero should feel frustrated or overwhelmed, and a moment of breathing/pausing should change everything.'},
      {night:4, theme:'Growing takes time', prompt:'Something in the story should be growing — and the hero should learn they can\'t speed it up, only tend to it.'},
      {night:5, theme:'Listen to the quiet', prompt:'The hero should discover something important in silence — something only patience reveals.'},
      {night:6, theme:'Trust the timing', prompt:'Something the hero wanted should arrive later than expected — and the timing should turn out to be perfect.'},
      {night:7, theme:'This moment is enough', prompt:'The story should end with the hero sitting in a moment of pure contentment — not needing anything to happen next.'},
    ],
    dailyWisdom:[
      "What's the rush? The good stuff happens when you slow down.",
      "The best things come to those who wait. Truly.",
      "When everything feels too much, just breathe. That's enough for now.",
      "You can't make a flower grow faster by pulling it. Just water it.",
      "Shh. Hear that? The quiet has something to tell you.",
      "It'll come. Maybe not today. But it'll come.",
      "Right here, right now, this moment — it's enough.",
    ],
  },
  {
    id:'deer', name:'Star Deer', emoji:'🦌', color:'#D4A860',
    description:'graceful, gentle, golden light',
    nameSuggestions:['Fawn','Maple','Solstice','Flicker'],
    virtue:'Gratitude', craft:'constellation', craftName:'The Deer', craftEmoji:'✦',
    constellationPoints:[[50,10],[35,25],[65,25],[30,50],[70,50],[40,80],[60,80]],
    storyPersonality:'Graceful and gentle. Stops to appreciate small beautiful things others walk past. Not preachy about gratitude — just naturally notices the good. Makes others slow down and see it too.',
    virtueKeywords:['gratitude','grateful','thankful','appreciation','noticing','blessing','thankfulness'],
    lessonBeats:[
      {night:1, theme:'Notice one good thing', prompt:'The hero should pause and notice one specific good thing in their day that they almost missed.'},
      {night:2, theme:'Say thank you and mean it', prompt:'The hero should thank someone in a way that\'s specific and personal — not a habit but a real moment.'},
      {night:3, theme:'The hard things teach too', prompt:'The hero should find something to be grateful for inside a difficult situation.'},
      {night:4, theme:'People, not things', prompt:'The hero should realise that the thing they\'re most grateful for is a person, not an object or achievement.'},
      {night:5, theme:'Give gratitude forward', prompt:'The hero should do something to make someone else feel appreciated and seen.'},
      {night:6, theme:'Your ordinary is magic', prompt:'The hero should see their ordinary everyday life through fresh eyes — and be stunned by how extraordinary it actually is.'},
      {night:7, theme:'Enough', prompt:'The story should end with the hero feeling genuinely full — not wanting more, just grateful for exactly what they have.'},
    ],
    dailyWisdom:[
      "What's one good thing that happened today? There's always one.",
      "When you say thank you, look them in the eyes. It changes everything.",
      "Even hard days are hiding something good. Can you find it?",
      "The best things in your life aren't things.",
      "Someone did something kind for you today. Did you notice?",
      "Your regular Tuesday? Somebody somewhere is wishing for it.",
      "You have enough. You are enough. Right now.",
    ],
  },
  {
    id:'frog', name:'Dream Frog', emoji:'🐸', color:'#80C870',
    description:'happy, bouncy, always optimistic',
    nameSuggestions:['Mossy','Puddle','Dewdrop','Lily'],
    virtue:'Joy', craft:'constellation', craftName:'The Frog', craftEmoji:'✦',
    constellationPoints:[[30,25],[50,10],[70,25],[80,50],[60,70],[40,70],[20,50]],
    storyPersonality:'Irrepressibly happy. Finds delight in puddles, mud, rain, bugs — things others find gross or boring. Not naive — genuinely joyful. Shows that joy is a choice and a practice, not luck.',
    virtueKeywords:['joy','happiness','happy','fun','delight','cheerful','optimism','positive','silly'],
    lessonBeats:[
      {night:1, theme:'Find the fun', prompt:'The hero should find something genuinely fun and delightful in a situation that seemed boring or ordinary.'},
      {night:2, theme:'Laugh at yourself', prompt:'The hero should make a silly mistake and laugh about it — showing that not everything needs to be serious.'},
      {night:3, theme:'Share the giggle', prompt:'The hero should make someone else laugh or smile — spreading joy intentionally.'},
      {night:4, theme:'Joy in the rain', prompt:'Something should go wrong, and the hero should find joy anyway — not by ignoring the problem but by choosing their response to it.'},
      {night:5, theme:'Celebrate small wins', prompt:'The hero should celebrate something tiny — a small victory that others might not notice.'},
      {night:6, theme:'The joy of trying', prompt:'The hero should try something new and find that the joy was in the trying, not the result.'},
      {night:7, theme:'Joy is a gift you give', prompt:'The story should end with the hero realising that their joy made everyone around them a little happier too.'},
    ],
    dailyWisdom:[
      "I bet there's something fun hiding in today. Let's find it!",
      "Did something silly happen? Good. Silly is underrated.",
      "You know what's free and unlimited? Making someone smile.",
      "It's raining? PERFECT. Do you know how fun rain is?",
      "You did a thing today. Even a small thing. Let's celebrate!",
      "The best part of trying isn't winning. It's the trying part.",
      "Your happiness is contagious. Did you know that?",
    ],
  },
  {
    id:'otter', name:'River Otter', emoji:'🦦', color:'#C8A878',
    description:'playful, curious, loves everything',
    nameSuggestions:['Pebble','Kelp','Ripple','Dew'],
    virtue:'Friendship', craft:'constellation', craftName:'The Otter', craftEmoji:'✦',
    constellationPoints:[[15,40],[30,20],[50,15],[70,20],[85,40],[70,65],[35,65]],
    storyPersonality:'Playful and social. Can\'t sit still. Drags friends into adventures. But also: listens carefully, remembers what you said yesterday, and always saves you the good rock. Shows friendship through action.',
    virtueKeywords:['friendship','friends','sharing','together','teamwork','cooperation','playing','inclusion'],
    lessonBeats:[
      {night:1, theme:'Say hello first', prompt:'The hero should make the first move to befriend someone new — a simple hello that changes a day.'},
      {night:2, theme:'Listen like you mean it', prompt:'The hero should listen to a friend carefully enough to remember something small — and that remembering should matter.'},
      {night:3, theme:'Share the good stuff', prompt:'The hero should share something they love with a friend — and find that sharing made it better.'},
      {night:4, theme:'Friends disagree', prompt:'The hero and a friend should disagree about something — and find their way back to each other without either one "winning."'},
      {night:5, theme:'Show up on the bad days', prompt:'The hero should show up for a friend who is having a bad day — not to fix it, just to be there.'},
      {night:6, theme:'Let new friends in', prompt:'The hero should include someone who was on the outside — expanding the circle without shrinking it.'},
      {night:7, theme:'Friends make you more you', prompt:'The story should end with the hero realising that their friends don\'t change who they are — they help them become more of it.'},
    ],
    dailyWisdom:[
      "Someone near you could use a 'hello' today. You could be the one.",
      "When your friend talks, listen with your whole face. They can tell.",
      "The best things are better when you share them with someone.",
      "Friends don't always agree. That's normal. You figure it out.",
      "Sometimes just sitting next to someone is the best thing you can do.",
      "There's always room for one more. Always.",
      "Your friends don't make you different. They make you more you.",
    ],
  },
  {
    id:'penguin', name:'Ice Penguin', emoji:'🐧', color:'#A0C8E0',
    description:'waddly, funny, surprisingly brave',
    nameSuggestions:['Pebble','Floe','Blizzard','Nook'],
    virtue:'Honesty', craft:'constellation', craftName:'The Penguin', craftEmoji:'✦',
    constellationPoints:[[50,10],[35,25],[65,25],[30,50],[70,50],[40,78],[60,78]],
    storyPersonality:'Awkward, honest to a fault, accidentally funny. Says what everyone is thinking. Not mean — just transparent. Shows that honesty is brave and sometimes uncomfortable but always builds trust.',
    virtueKeywords:['honesty','honest','truth','telling the truth','trust','integrity','sincere'],
    lessonBeats:[
      {night:1, theme:'Truth feels different', prompt:'The hero should notice the physical difference between how truth and lies feel — truth is lighter even when it\'s harder.'},
      {night:2, theme:'Say the hard thing gently', prompt:'The hero should tell someone a difficult truth — but do it with kindness.'},
      {night:3, theme:'Honest with yourself', prompt:'The hero should admit something to themselves they\'ve been avoiding — self-honesty.'},
      {night:4, theme:'When honesty costs', prompt:'The hero should tell the truth even though it means losing something — and the story should honour that sacrifice.'},
      {night:5, theme:'Trust is built on truth', prompt:'Someone should trust the hero specifically because the hero has been consistently honest.'},
      {night:6, theme:'The whole truth', prompt:'The hero should realise that a half-truth can be worse than a lie — and choose to share the full picture.'},
      {night:7, theme:'Honesty is freedom', prompt:'The story should end with the hero feeling lighter after being honest — showing that truth is freeing even when it\'s hard.'},
    ],
    dailyWisdom:[
      "Truth feels different in your body. Like putting something down.",
      "You can say a hard thing and still say it softly.",
      "The hardest person to be honest with is yourself.",
      "Telling the truth sometimes costs. It's still worth it.",
      "People trust you because you tell the truth. Even the tricky parts.",
      "A half-truth is a whole problem. Say all of it.",
      "After you tell the truth, notice how much lighter you feel.",
    ],
  },
  {
    id:'hedgehog', name:'Glow Hog', emoji:'🦔', color:'#D4A878',
    description:'shy at first, heart of gold',
    nameSuggestions:['Prickle','Bramble','Acorn','Noodle'],
    virtue:'Vulnerability', craft:'constellation', craftName:'The Hedgehog', craftEmoji:'✦',
    constellationPoints:[[50,15],[30,20],[70,20],[20,45],[80,45],[35,72],[65,72]],
    storyPersonality:'Curls up in a ball when scared. Prickly outside, impossibly soft inside. Slowly unfurls as trust builds. Shows that letting people in — despite the risk — is the bravest thing of all.',
    virtueKeywords:['vulnerability','feelings','emotions','opening up','trust','sensitivity','shy','sensitive'],
    lessonBeats:[
      {night:1, theme:'Walls keep safe but also keep lonely', prompt:'The hero should notice that the thing protecting them is also isolating them.'},
      {night:2, theme:'One person is enough', prompt:'The hero should let their guard down with just one trusted person — and that small opening should feel enormous.'},
      {night:3, theme:'Feelings aren\'t weakness', prompt:'The hero should express a feeling — sadness, fear, love — and someone should treat it as strength.'},
      {night:4, theme:'Ask for what you need', prompt:'The hero should ask for help or comfort directly, instead of hoping someone notices.'},
      {night:5, theme:'Let them see the real you', prompt:'The hero should show someone their true self — quirks and all — and be accepted completely.'},
      {night:6, theme:'Getting hurt is surviving', prompt:'The hero should be let down after being vulnerable — and survive it. Showing that the risk is survivable.'},
      {night:7, theme:'Open is stronger than closed', prompt:'The story should end with the hero choosing to stay open despite past hurt — showing that vulnerability is the ultimate courage.'},
    ],
    dailyWisdom:[
      "Your walls keep you safe. But they also keep you alone.",
      "You don't have to open up to everyone. Just one person is enough.",
      "Feelings aren't weakness. They're the bravest part of you.",
      "You're allowed to say what you need. Out loud.",
      "The real you — the weird, messy, specific you — that's the loveable one.",
      "Someone might let you down. You'll survive. You always do.",
      "Staying open after being hurt? That's the strongest thing there is.",
    ],
  },
  {
    id:'lion', name:'Sun Lion', emoji:'🦁', color:'#F0B840',
    description:'born to lead, loves cuddles secretly',
    nameSuggestions:['Soleil','Mane','Kibo','Zuri'],
    virtue:'Leadership', craft:'constellation', craftName:'The Lion', craftEmoji:'✦',
    constellationPoints:[[50,8],[25,25],[75,25],[15,50],[85,50],[30,78],[70,78]],
    storyPersonality:'Confident but not arrogant. Leads by doing, not telling. Secretly needs reassurance. Shows that real leadership is service — going first so others feel safe to follow.',
    virtueKeywords:['leadership','leader','responsibility','taking charge','brave','standing up','confidence'],
    lessonBeats:[
      {night:1, theme:'Go first', prompt:'The hero should be the first one to do something scary — not because they\'re not afraid, but because someone needs to go first.'},
      {night:2, theme:'Listen to your team', prompt:'The hero should change their plan because someone else had a better idea — showing that leadership includes listening.'},
      {night:3, theme:'Take responsibility', prompt:'Something should go wrong and the hero should take responsibility instead of blaming — even when it wasn\'t entirely their fault.'},
      {night:4, theme:'Lift others up', prompt:'The hero should help someone else shine — stepping back so someone else can step forward.'},
      {night:5, theme:'Leaders need help too', prompt:'The hero should admit they\'re struggling and accept support — showing that leaders aren\'t supposed to carry everything alone.'},
      {night:6, theme:'The hard decision', prompt:'The hero should make a difficult decision that\'s right for everyone, not just for themselves.'},
      {night:7, theme:'Lead by being kind', prompt:'The story should end with the hero leading through kindness and example — the quietest, most powerful kind of leadership.'},
    ],
    dailyWisdom:[
      "Someone has to go first. Why not you?",
      "The best leaders don't talk the most. They listen the most.",
      "When things go wrong, the leader says 'that was me' — even when it wasn't.",
      "Making someone else look good? That's what leaders actually do.",
      "Even leaders need someone. Especially leaders.",
      "The right thing and the easy thing are usually different things.",
      "The strongest way to lead is by being kind. Always.",
    ],
  },
  {
    id:'turtle', name:'Tide Turtle', emoji:'🐢', color:'#88C8A0',
    description:'old soul, patient, full of wisdom',
    nameSuggestions:['Coral','Tide','Mossy','Shelly'],
    virtue:'Empathy', craft:'constellation', craftName:'The Turtle', craftEmoji:'✦',
    constellationPoints:[[40,15],[60,15],[75,35],[70,60],[50,75],[30,60],[25,35]],
    storyPersonality:'Old soul. Moves slowly but sees deeply. Feels what others feel. Carries the stories of everyone they\'ve met. Shows empathy not as a skill but as a way of being in the world.',
    virtueKeywords:['empathy','understanding others','feelings','perspective','compassion','walking in shoes','seeing others'],
    lessonBeats:[
      {night:1, theme:'Everyone has a story', prompt:'The hero should discover the backstory of someone they\'d made assumptions about — and those assumptions should be completely wrong.'},
      {night:2, theme:'How would that feel?', prompt:'The hero should imagine themselves in someone else\'s situation — and that imagining should change how they act.'},
      {night:3, theme:'Words land differently', prompt:'The hero should say something that lands differently than intended — and learn that impact matters more than intention.'},
      {night:4, theme:'Sit with someone\'s sadness', prompt:'Instead of trying to fix someone\'s sadness, the hero should simply sit with them in it.'},
      {night:5, theme:'Joy for someone else', prompt:'The hero should feel genuinely happy about someone else\'s success — even when they wanted it for themselves.'},
      {night:6, theme:'Understand, don\'t agree', prompt:'The hero should understand why someone did something hurtful — without excusing it. Empathy with boundaries.'},
      {night:7, theme:'Connection', prompt:'The story should end with a moment of deep, wordless understanding between two characters — empathy as the bridge between all people.'},
    ],
    dailyWisdom:[
      "That person who annoyed you today? They have a whole life you don't know about.",
      "Before you decide what to say, imagine hearing it.",
      "The same words can feel totally different to someone else.",
      "Sometimes people don't need you to fix it. They need you to sit with it.",
      "Being happy for someone else is one of the hardest, best things.",
      "You can understand someone without agreeing with them.",
      "We're all just walking each other home.",
    ],
  },
  {
    id:'elephant', name:'Cloud Elephant', emoji:'🐘', color:'#B0C8E0',
    description:'big-hearted, never forgets a friend',
    nameSuggestions:['Nimbus','Cinder','Petal','Rogue'],
    virtue:'Generosity', craft:'constellation', craftName:'The Elephant', craftEmoji:'✦',
    constellationPoints:[[30,15],[55,10],[75,20],[80,45],[65,70],[40,75],[20,50]],
    storyPersonality:'Enormous heart. Gives without thinking. Carries others when they\'re tired. Shows that generosity isn\'t about having a lot — it\'s about sharing whatever you have.',
    virtueKeywords:['generosity','generous','giving','sharing','selfless','helping others','charity'],
    lessonBeats:[
      {night:1, theme:'Give what you can', prompt:'The hero should share something they have — even if it\'s small — with someone who needs it.'},
      {night:2, theme:'Time is the best gift', prompt:'The hero should give someone their time and attention — and it should be more valuable than any object.'},
      {night:3, theme:'Give without expecting', prompt:'The hero should give something with no expectation of return — and the story should honour that.'},
      {night:4, theme:'Generosity when you have little', prompt:'The hero should be generous despite having very little themselves — showing that generosity isn\'t about wealth.'},
      {night:5, theme:'Accept generosity', prompt:'Someone should be generous to the hero, and the hero should learn to accept gracefully.'},
      {night:6, theme:'Sharing makes more', prompt:'Something the hero shares should multiply or become better through sharing — defying the logic that giving means having less.'},
      {night:7, theme:'A generous heart is full', prompt:'The story should end with the hero feeling fuller after giving — not emptier. The paradox of generosity.'},
    ],
    dailyWisdom:[
      "You always have something to give. Always.",
      "The best gift isn't a thing. It's your time.",
      "Give it. Don't count. Don't wait for thank you.",
      "You don't need a lot to give a lot.",
      "Someone gave you something today. Did you let yourself receive it?",
      "When you share, you don't have less. You have more.",
      "A heart that gives is a heart that's full.",
    ],
  },
  {
    id:'axolotl', name:'Star Axolotl', emoji:'🐠', color:'#F09898',
    description:'the rarest find, uniquely magical',
    nameSuggestions:['Lotl','Gilly','Bloop','Frilly'],
    virtue:'Self-acceptance', craft:'constellation', craftName:'The Axolotl', craftEmoji:'✦',
    constellationPoints:[[25,30],[40,10],[60,10],[75,30],[70,55],[50,75],[30,55]],
    storyPersonality:'Wonderfully weird. Knows they\'re different and has made peace with it. Not trying to fit in — but not trying to stand out either. Just fully, unapologetically themselves.',
    virtueKeywords:['self-acceptance','accepting yourself','being different','unique','weird','self-love','identity'],
    lessonBeats:[
      {night:1, theme:'Different is real', prompt:'The hero should notice something about themselves that\'s different from everyone else — and the story should treat it as fact, not problem.'},
      {night:2, theme:'Stop comparing', prompt:'The hero should catch themselves comparing to someone else — and choose to stop.'},
      {night:3, theme:'Your weird is your best', prompt:'The thing that makes the hero different should turn out to be exactly what\'s needed.'},
      {night:4, theme:'Not everyone will get you', prompt:'Someone should not understand the hero — and the hero should be okay with it.'},
      {night:5, theme:'Find your people', prompt:'The hero should find someone who gets them completely — showing that acceptance starts with finding the right audience.'},
      {night:6, theme:'Change for you, not them', prompt:'The hero should choose to change something about themselves — but only because they want to, not because anyone asked.'},
      {night:7, theme:'You were always enough', prompt:'The story should end with the hero looking in a mirror (literal or metaphorical) and liking what they see — fully and simply.'},
    ],
    dailyWisdom:[
      "You're different. That's not a problem. That's the point.",
      "Comparing yourself to someone else is like comparing the moon to a lamp. Why?",
      "That weird thing about you? It's your superpower. Give it time.",
      "Not everyone will get you. That's fine. You're not for everyone.",
      "Somewhere out there is someone who thinks exactly like you. You'll find them.",
      "If you're going to change, change because you want to. Nobody else gets a vote.",
      "Look at yourself. Really look. You were always enough.",
    ],
  },
  {
    id:'koala', name:'Gum Koala', emoji:'🐨', color:'#B0C0D0',
    description:'peaceful, expert napper, dreamy',
    nameSuggestions:['Euca','Snoozy','Foggy','Bluegum'],
    virtue:'Peace', craft:'constellation', craftName:'The Koala', craftEmoji:'✦',
    constellationPoints:[[40,12],[60,12],[25,35],[75,35],[35,62],[65,62],[50,82]],
    storyPersonality:'The calmest presence in any story. Not passive — peacefully certain. When chaos erupts, they\'re the still point. Shows that peace is not the absence of trouble — it\'s the choice not to add to it.',
    virtueKeywords:['peace','peaceful','calm','serenity','conflict resolution','harmony','stillness','mindfulness'],
    lessonBeats:[
      {night:1, theme:'Be the calm one', prompt:'Everyone around the hero should be stressed or panicking — and the hero should stay calm, and that calm should help.'},
      {night:2, theme:'Don\'t add fuel', prompt:'The hero should resist the urge to escalate a conflict — choosing not to react.'},
      {night:3, theme:'Find your quiet place', prompt:'The hero should find or create a mental space of calm — a technique they can use again.'},
      {night:4, theme:'Peace takes strength', prompt:'The hero should choose the peaceful path when fighting would be easier — showing peace as active and brave.'},
      {night:5, theme:'Make peace between others', prompt:'The hero should help two others resolve a conflict — not by taking sides but by helping both feel heard.'},
      {night:6, theme:'Inner storms pass', prompt:'The hero should experience inner turmoil — anger, anxiety — and discover that it passes if they let it.'},
      {night:7, theme:'Peace is a gift you carry', prompt:'The story should end with the hero carrying peace with them like a lantern — bringing calm to wherever they go.'},
    ],
    dailyWisdom:[
      "When everyone is loud, the quiet one changes everything.",
      "You don't have to react. You get to choose.",
      "Close your eyes. You have a quiet place inside. It's always there.",
      "Choosing peace when you could fight? That takes more strength.",
      "You can't make people agree. But you can make them feel heard.",
      "That big feeling you have right now? Watch it. It's going to pass.",
      "You carry peace with you wherever you go. Like a light.",
    ],
  },
  {
    id:'hummingbird', name:'Bloom Bird', emoji:'🐦', color:'#F080A0',
    description:'lightning-fast, tiny heart, pure joy',
    nameSuggestions:['Zinnia','Flutter','Nectar','Jewel'],
    virtue:'Curiosity', craft:'constellation', craftName:'The Hummingbird', craftEmoji:'✦',
    constellationPoints:[[20,35],[35,15],[55,10],[75,20],[80,45],[60,65],[40,55]],
    storyPersonality:'Can\'t stop moving. Fascinated by everything. Asks questions faster than anyone can answer. Not scattered — intensely focused on whatever has caught their attention right now. Shows that curiosity is the root of all learning.',
    virtueKeywords:['curiosity','curious','questions','exploring','learning','discovering','wonder','adventurous'],
    lessonBeats:[
      {night:1, theme:'Ask the question nobody asked', prompt:'The hero should ask a question that everyone else took for granted — and the answer should change everything.'},
      {night:2, theme:'Follow the thread', prompt:'The hero should follow one small curiosity and it should lead somewhere wonderful and unexpected.'},
      {night:3, theme:'Try something new', prompt:'The hero should try something they\'ve never done before — purely because they wondered what it would be like.'},
      {night:4, theme:'Wrong answers teach', prompt:'The hero should guess wrong — and that wrong guess should teach them something more interesting than the right answer.'},
      {night:5, theme:'Be curious about people', prompt:'The hero should be curious about a person — their story, their feelings — and that curiosity should deepen the relationship.'},
      {night:6, theme:'Wonder is enough', prompt:'The hero should encounter something they can\'t explain — and instead of needing an answer, they should enjoy the mystery.'},
      {night:7, theme:'Never stop asking', prompt:'The story should end with the hero asking a new question — showing that curiosity doesn\'t end, it multiplies.'},
    ],
    dailyWisdom:[
      "What's a question nobody asked today? Ask it.",
      "Follow the thing that interests you. It knows where to go.",
      "You've never done that before? Perfect. Let's try it.",
      "Wrong answers are just right answers to a different question.",
      "Be as curious about people as you are about everything else.",
      "Not everything needs an answer. Some things are better as questions.",
      "The best people never stop asking why.",
    ],
  },
];

export const getCreature = (id: string): CreatureDef =>
  CREATURES.find(c => c.id === id) ?? CREATURES[0];

export const getCreatureByVirtueKeyword = (keyword: string): CreatureDef | null => {
  const lower = keyword.toLowerCase();
  return CREATURES.find(c => c.virtueKeywords.some(k => lower.includes(k))) ?? null;
};

export const getCreatureByVirtue = (virtue: string): CreatureDef | null => {
  const lower = virtue.toLowerCase();
  return CREATURES.find(c => c.virtue.toLowerCase() === lower) ?? null;
};
